//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_hopital
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gest_RDVEntities : DbContext
    {
        public Gest_RDVEntities()
            : base("name=Gest_RDVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<medecin> medecins { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<RDV> RDVs { get; set; }
    }
}
